### ISSUE TITLE
Notification while uploading

### ISSUE THREAD

**Issue by GoOz** [vookimedlo/alfred-various-screenshots#2]
Hey there, first of all thank you very much for this workflow! I used to do it with the workflow "Screenshots" but since the last Dropbox update about the public folder, it wouldn't work anymore and the developer was M.I.A.

Anyhow, it works great for me but I have a tiny enhancement to suggest. For me it took time (like 3 to 5 seconds, I don't have a speedy internet connection) to upload the screenshot to dropbox and paste the link to the clipboard.
So I suggest a notification while the screenshot is uploading to reassure the user that nothing's broken, it just takes some time.

That's pretty much it. Thanks again.

**Comment by vookimedlo** [comment]
Hi there, I added the notification for Dropbox upload process.
Enjoy it. 

Release: [v2017_12_02][1]

[1]: https://github.com/vookimedlo/alfred-various-screenshots/releases/tag/v2017_12_02
