### ISSUE TITLE
Set default save directory in Dropbox

### ISSUE THREAD

**Issue by turkeyphant** [vookimedlo/alfred-various-screenshots#3]
Can't seem to work out how to customise this?

**Comment by vookimedlo** [comment]
What do you mean by 'default save directory in Dropbox'?
- Do you want to save just a screenshot in Dropbox without sharing it? Right now, all images are saved to the ~/Desktop folder. I can make it configurable if you want it.
- Do you want  to share a screenshot via dropbox? Then, the dropbox folder with shared screenshots is not configurable in this workflow, but directly on the Dropbox configuration page. See 'App folder name' below. Once you change it, this workflow will upload further screenshots to the new location automagically.
![image](https://user-images.githubusercontent.com/2312301/39447213-5de855ee-4cc1-11e8-80b4-25869414e38b.png)

**Comment by turkeyphant** [comment]
I want,
a) to be able to save by default to any writeable directory on the filesystem and
(nice to have) b) to have the link copied to clipboard if it happened to be a Dropbox (or Google Drive(?) directory)

Is this feasible?

**Comment by vookimedlo** [comment]
Just item "a)" is feasible - new released version https://github.com/vookimedlo/alfred-various-screenshots/releases/tag/v2018_05_01

Default local screenshots folder `~/Desktop` can be changed by the workflow `DefaultLocalScreenshotFolder` variable.
![alfred-various-screenshots-variable-local](https://user-images.githubusercontent.com/2312301/39486576-f096bf8c-4d7c-11e8-86c2-0900f8ca79d0.png)
